# -*- coding: utf-8 -*-
"""Untitled8_(1)_(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2O8c59fVGM5VgfaS0VJxlM_0yoj9QV1
"""





import pandas as pd


df = pd.read_csv("/content/phishing.csv")


df.head()

# Taille du dataset
print("Nombre de lignes et colonnes :", df.shape)

# Types de données
print(df.dtypes)

# Résumé statistique
print(df.describe())

# Valeurs manquantes
print(df.isnull().sum())

# Supprimer les colonnes inutiles si besoin
df = df.drop(columns=["index", "id"], errors='ignore')  # à adapter selon le dataset

# Supprimer les doublons
df = df.drop_duplicates()

# Supprimer ou remplir les valeurs manquantes
df = df.dropna()

import seaborn as sns
import matplotlib.pyplot as plt

# Visualisation des classes phishing vs légitimes
sns.countplot(x='class', data=df)
plt.title("Répartition des sites : Phishing vs Légitime")
plt.xlabel("Classe (1 = phishing, -1 = légitime)")  # ou adapte selon ta compréhension
plt.ylabel("Nombre d'exemples")
plt.show()

# ✅ 1. Séparer X (les caractéristiques) et y (la cible)
X = df.drop(['Index', 'class'], axis=1)  # on enlève l’index et la classe
y = df['class']

# ✅ 2. Vérifier les dimensions
print("Dimensions de X :", X.shape)
print("Dimensions de y :", y.shape)

# ✅ 3. Exemple de valeurs
print("Exemples de X :")
print(X.head())

print("Exemples de y :")
print(y.value_counts())

pip install pandas scikit-learn joblib streamlit

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import joblib
import os

# 1. Charger les données avec gestion d'erreurs
try:
    # Ajustez le chemin selon votre environnement
    # Pour Colab: '/content/phishing.csv'
    # Pour local: 'phishing.csv' ou le chemin complet
    df = pd.read_csv('phishing.csv')
    print(f"Dataset chargé avec succès: {df.shape}")
    print("Colonnes disponibles:")
    print(df.columns.tolist())

except FileNotFoundError:
    print("❌ Erreur: Fichier 'phishing.csv' non trouvé")
    print("Vérifiez le chemin du fichier")
    exit()

# 2. Exploration rapide des données
print(f"\nInformations sur le dataset:")
print(f"Shape: {df.shape}")
print(f"Valeurs manquantes: {df.isnull().sum().sum()}")

# Vérifier les noms de colonnes possibles pour la variable cible
target_candidates = ['CLASS_LABEL', 'class', 'label', 'target', 'phishing']
target_col = None

for col in target_candidates:
    if col in df.columns:
        target_col = col
        break

if target_col is None:
    print("❌ Erreur: Colonne cible non trouvée")
    print("Colonnes disponibles:", df.columns.tolist())
    exit()

print(f"Colonne cible utilisée: {target_col}")
print(f"Distribution des classes: \n{df[target_col].value_counts()}")

# 3. Préparation des données
X = df.drop(target_col, axis=1)
y = df[target_col]

# Mapper les labels si nécessaire (-1/1 vers 0/1)
if y.min() == -1:
    y = y.map({-1: 0, 1: 1})
    print("Labels mappés de {-1, 1} vers {0, 1}")

# Vérifier s'il y a des colonnes non-numériques
non_numeric = X.select_dtypes(exclude=[np.number]).columns
if len(non_numeric) > 0:
    print(f"⚠️ Colonnes non-numériques détectées: {non_numeric.tolist()}")
    # Vous pourriez vouloir les encoder ou les supprimer
    X = X.select_dtypes(include=[np.number])
    print(f"Utilisation des colonnes numériques seulement: {X.shape}")

# 4. Division train/test
print(f"\nDivision des données...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
print(f"Train: {X_train.shape}, Test: {X_test.shape}")

# 5. Normalisation
print("Normalisation des données...")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 6. Modèle de base
print("\n" + "="*50)
print("MODÈLE RANDOM FOREST - VERSION DE BASE")
print("="*50)

rf_base = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
rf_base.fit(X_train_scaled, y_train)

y_pred_base = rf_base.predict(X_test_scaled)

print(f"Accuracy: {accuracy_score(y_test, y_pred_base):.4f}")
print(f"\nMatrice de confusion:")
print(confusion_matrix(y_test, y_pred_base))
print(f"\nRapport de classification:")
print(classification_report(y_test, y_pred_base))

# 7. Optimisation des hyperparamètres
print("\n" + "="*50)
print("OPTIMISATION DES HYPERPARAMÈTRES")
print("="*50)

param_grid = {
    'n_estimators': [100, 150, 200],
    'max_depth': [None, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2]
}

print("Recherche des meilleurs paramètres...")
grid_search = GridSearchCV(
    RandomForestClassifier(random_state=42, n_jobs=-1),
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train_scaled, y_train)

print(f"Meilleurs paramètres: {grid_search.best_params_}")
print(f"Meilleur score F1 (CV): {grid_search.best_score_:.4f}")

# 8. Évaluation du modèle optimisé
print("\n" + "="*50)
print("MODÈLE OPTIMISÉ - ÉVALUATION FINALE")
print("="*50)

best_rf = grid_search.best_estimator_
y_pred_optimized = best_rf.predict(X_test_scaled)

print(f"Accuracy: {accuracy_score(y_test, y_pred_optimized):.4f}")
print(f"\nMatrice de confusion:")
print(confusion_matrix(y_test, y_pred_optimized))
print(f"\nRapport de classification:")
print(classification_report(y_test, y_pred_optimized))

# 9. Importance des features
print("\n" + "="*50)
print("IMPORTANCE DES FEATURES (TOP 10)")
print("="*50)

feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': best_rf.feature_importances_
}).sort_values('importance', ascending=False)

print(feature_importance.head(10))

# 10. Sauvegarde des modèles
print("\n" + "="*50)
print("SAUVEGARDE DES MODÈLES")
print("="*50)

try:
    # Créer le dossier models s'il n'existe pas
    os.makedirs('models', exist_ok=True)

    # Sauvegarder le modèle et le scaler
    joblib.dump(best_rf, 'models/phishing_rf_model.pkl')
    joblib.dump(scaler, 'models/phishing_scaler.pkl')

    print("✅ Modèle sauvegardé: models/phishing_rf_model.pkl")
    print("✅ Scaler sauvegardé: models/phishing_scaler.pkl")

    # Sauvegarder aussi les noms des colonnes
    joblib.dump(X.columns.tolist(), 'models/feature_names.pkl')
    print("✅ Noms des features sauvegardés: models/feature_names.pkl")

except Exception as e:
    print(f"❌ Erreur lors de la sauvegarde: {e}")

print("\n" + "="*50)
print("ENTRAÎNEMENT TERMINÉ !")
print("="*50)

import streamlit as st
import numpy as np
import joblib
import os
import pandas as pd

st.set_page_config(
    page_title="Détection de Phishing",
    page_icon="🔍",
    layout="wide"
)

st.title("🔍 Détection de Phishing")
st.markdown("---")

# Vérification et chargement des modèles
@st.cache_resource
def load_models():
    try:
        # Chemins possibles pour les modèles
        model_paths = [
            'models/phishing_rf_model.pkl',
            'phishing_rf.pkl',
            'phishing_rf_model.pkl',
            './models/phishing_rf_model.pkl',
            '../models/phishing_rf_model.pkl'
        ]

        scaler_paths = [
            'models/phishing_scaler.pkl',
            'phishing_scaler.pkl',
            './models/phishing_scaler.pkl',
            '../models/phishing_scaler.pkl'
        ]

        model = None
        scaler = None

        # Charger le modèle
        for path in model_paths:
            if os.path.exists(path):
                model = joblib.load(path)
                st.success(f"✅ Modèle chargé depuis: {path}")
                break

        # Charger le scaler
        for path in scaler_paths:
            if os.path.exists(path):
                scaler = joblib.load(path)
                st.success(f"✅ Scaler chargé depuis: {path}")
                break

        if model is None:
            st.error("❌ Modèle non trouvé. Vérifiez les chemins ou exécutez l'entraînement.")
            st.info("💡 Chemins recherchés: " + ", ".join(model_paths))
            return None, None

        if scaler is None:
            st.warning("⚠️ Scaler non trouvé. Utilisation sans normalisation.")

        return model, scaler

    except Exception as e:
        st.error(f"❌ Erreur lors du chargement: {str(e)}")
        return None, None

# Définir les descriptions des caractéristiques
feature_descriptions = {
    "having_IP_Address": "Utilise une adresse IP au lieu d'un nom de domaine",
    "URL_Length": "Longueur de l'URL",
    "Shortining_Service": "Utilise un service de raccourcissement d'URL",
    "having_At_Symbol": "Contient le symbole @ dans l'URL",
    "double_slash_redirecting": "Double slash de redirection",
    "Prefix_Suffix": "Préfixe-suffixe dans le nom de domaine",
    "having_Sub_Domain": "Nombre de sous-domaines",
    "SSLfinal_State": "État du certificat SSL",
    "Domain_registeration_length": "Durée d'enregistrement du domaine",
    "Favicon": "Favicon chargé depuis un domaine externe",
    "port": "Utilise un port non-standard",
    "HTTPS_token": "Token HTTPS dans le nom de domaine",
    "Request_URL": "Pourcentage d'objets chargés depuis un autre domaine",
    "URL_of_Anchor": "URLs des ancres",
    "Links_in_tags": "Liens dans les balises META, SCRIPT et LINK",
    "SFH": "Server Form Handler",
    "Submitting_to_email": "Soumission à une adresse email",
    "Abnormal_URL": "URL anormale",
    "Redirect": "Redirection",
    "on_mouseover": "Changement de statut sur mouseover",
    "RightClick": "Désactivation du clic droit",
    "popUpWidnow": "Fenêtres popup",
    "Iframe": "Utilisation d'IFrame",
    "age_of_domain": "Âge du domaine",
    "DNSRecord": "Enregistrement DNS",
    "web_traffic": "Trafic web",
    "Page_Rank": "Classement de page",
    "Google_Index": "Indexation Google",
    "Links_pointing_to_page": "Liens pointant vers la page",
    "Statistical_report": "Rapport statistique"
}

# Charger les modèles
model, scaler = load_models()

if model is not None:

    # Section pour URL rapide (optionnelle)
    st.markdown("### 🚀 Test rapide avec des valeurs prédéfinies")
    col_test1, col_test2 = st.columns(2)

    with col_test1:
        if st.button("🟢 Tester un site légitime"):
            st.session_state.test_values = [0] * 30  # Valeurs sûres

    with col_test2:
        if st.button("🔴 Tester un site suspect"):
            st.session_state.test_values = [1, 1, 1, 1, 0, 1, 3, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]

    st.markdown("---")
    st.markdown("### 📊 Analyse détaillée")
    st.markdown("Ajustez les paramètres ci-dessous pour analyser un site web:")

    # Créer les inputs avec des descriptions
    inputs = []
    feature_names = list(feature_descriptions.keys())

    # Utiliser un expander pour une meilleure organisation
    with st.expander("🔧 Paramètres avancés", expanded=True):
        # Créer les colonnes
        num_cols = 3
        cols = st.columns(num_cols)

        for i, feature_name in enumerate(feature_names):
            col_idx = i % num_cols

            with cols[col_idx]:
                # Utiliser les valeurs de test si elles existent
                default_val = 0.0
                if hasattr(st.session_state, 'test_values') and st.session_state.test_values:
                    default_val = float(st.session_state.test_values[i])

                val = st.number_input(
                    feature_name,
                    value=default_val,
                    help=feature_descriptions[feature_name],
                    key=f"input_{i}",
                    min_value=-1.0,
                    max_value=10.0,
                    step=0.1
                )
                inputs.append(val)

    # Bouton d'analyse centré
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        analyze_button = st.button("🔍 Analyser le site", type="primary", use_container_width=True)

    if analyze_button:
        try:
            X = np.array(inputs).reshape(1, -1)

            # Appliquer le scaler si disponible
            if scaler is not None:
                X_scaled = scaler.transform(X)
            else:
                X_scaled = X

            prediction = model.predict(X_scaled)[0]
            probabilities = model.predict_proba(X_scaled)[0]

            st.markdown("---")
            st.markdown("### 📋 Résultats de l'analyse")

            if prediction == 1:
                st.error(f"⚠️ **SITE SUSPECT - PHISHING DÉTECTÉ !**")
                st.error(f"🎯 Probabilité de phishing: **{probabilities[1]:.1%}**")
                st.warning("🛡️ **Recommandation**: Ne pas visiter ce site ou saisir d'informations personnelles")
            else:
                st.success(f"✅ **SITE PROBABLEMENT LÉGITIME**")
                st.success(f"🎯 Probabilité de légitimité: **{probabilities[0]:.1%}**")
                st.info("ℹ️ **Note**: Cette analyse est basée sur des caractéristiques techniques. Restez vigilant.")

            # Afficher les probabilités détaillées
            col_prob1, col_prob2 = st.columns(2)
            with col_prob1:
                st.metric("Probabilité Légitime", f"{probabilities[0]:.1%}")
            with col_prob2:
                st.metric("Probabilité Phishing", f"{probabilities[1]:.1%}")

        except Exception as e:
            st.error(f"❌ Erreur lors de l'analyse: {str(e)}")
            st.info("💡 Vérifiez que les valeurs sont dans les bonnes plages")

else:
    st.error("❌ Impossible de charger les modèles.")

import numpy as np
import joblib
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

def load_or_create_model():
    """Charge le modèle ou en crée un de démonstration si les fichiers n'existent pas"""
    model_path = 'phishing_rf.pkl'
    scaler_path = 'phishing_scaler.pkl'

    try:
        # Tentative de chargement des modèles existants
        if os.path.exists(model_path) and os.path.exists(scaler_path):
            model = joblib.load(model_path)
            scaler = joblib.load(scaler_path)
            print("✅ Modèles chargés avec succès!")
            return model, scaler
        else:
            raise FileNotFoundError("Fichiers de modèle non trouvés")

    except Exception as e:
        print(f"⚠️ Impossible de charger les modèles: {str(e)}")
        print("🔧 Création d'un modèle de démonstration...")

        # Création d'un modèle de démonstration
        np.random.seed(42)
        X_demo = np.random.randn(1000, 30)
        # Règle simple pour créer des labels
        y_demo = (X_demo[:, :5].sum(axis=1) > 0).astype(int)

        # Entraînement du modèle de démonstration
        model = RandomForestClassifier(n_estimators=100, random_state=42)
        scaler = StandardScaler()

        X_scaled = scaler.fit_transform(X_demo)
        model.fit(X_scaled, y_demo)

        # Sauvegarde optionnelle
        try:
            joblib.dump(model, model_path)
            joblib.dump(scaler, scaler_path)
            print("💾 Modèle de démonstration sauvegardé")
        except:
            print("Impossible de sauvegarder le modèle")

        return model, scaler

def get_user_input():
    """Récupère les 30 caractéristiques de l'utilisateur"""
    print("\n🔍 DÉTECTEUR DE PHISHING")
    print("=" * 50)
    print("Veuillez entrer les 30 caractéristiques (valeurs entre -3 et 3 recommandées)")
    print("Appuyez sur Entrée pour utiliser la valeur par défaut (0.0)")
    print("-" * 50)

    inputs = []
    for i in range(30):
        while True:
            try:
                user_input = input(f"Feature_{i+1:02d}: ")
                if user_input.strip() == "":
                    val = 0.0
                else:
                    val = float(user_input)
                inputs.append(val)
                break
            except ValueError:
                print("❌ Veuillez entrer un nombre valide!")

    return inputs

def generate_random_input():
    """Génère des valeurs aléatoires pour test"""
    return np.random.randn(30).tolist()

def predict_phishing(model, scaler, inputs):
    """Effectue la prédiction de phishing"""
    try:
        # Préparation des données
        X = np.array(inputs).reshape(1, -1)
        Xs = scaler.transform(X)

        # Prédiction
        pred = model.predict(Xs)[0]
        probabilities = model.predict_proba(Xs)[0]
        prob_phishing = probabilities[1] if len(probabilities) > 1 else probabilities[0]
        prob_legitimate = probabilities[0] if len(probabilities) > 1 else 1 - probabilities[0]

        return pred, prob_phishing, prob_legitimate

    except Exception as e:
        print(f"❌ Erreur lors de la prédiction: {str(e)}")
        return None, None, None

def display_results(pred, prob_phishing, prob_legitimate):
    """Affiche les résultats de la prédiction"""
    print("\n" + "=" * 50)
    print("📊 RÉSULTATS DE L'ANALYSE")
    print("=" * 50)

    if pred == 1:
        print("⚠️  PHISHING DÉTECTÉ ⚠️")
        print(f"Probabilité de phishing: {prob_phishing:.2%}")
    else:
        print("✅ SITE LÉGITIME ✅")
        print(f"Probabilité de légitimité: {prob_legitimate:.2%}")

    print(f"\nDétail des probabilités:")
    print(f"  - Légitime: {prob_legitimate:.2%}")
    print(f"  - Phishing: {prob_phishing:.2%}")
    print("-" * 50)

def main():
    """Fonction principale"""
    try:
        # Chargement du modèle
        model, scaler = load_or_create_model()

        while True:
            print("\n" + "=" * 50)
            print("OPTIONS:")
            print("1. Entrer les valeurs manuellement")
            print("2. Générer des valeurs aléatoires")
            print("3. Quitter")
            print("=" * 50)

            choice = input("Votre choix (1-3): ").strip()

            if choice == '1':
                inputs = get_user_input()
            elif choice == '2':
                inputs = generate_random_input()
                print("🎲 Valeurs aléatoires générées:")
                for i, val in enumerate(inputs):
                    print(f"Feature_{i+1:02d}: {val:.3f}")
            elif choice == '3':
                print("👋 Au revoir!")
                break
            else:
                print("❌ Choix invalide!")
                continue

            # Prédiction
            pred, prob_phishing, prob_legitimate = predict_phishing(model, scaler, inputs)

            if pred is not None:
                display_results(pred, prob_phishing, prob_legitimate)

            # Demander si continuer
            continue_choice = input("\nVoulez-vous faire une autre prédiction? (o/n): ").strip().lower()
            if continue_choice not in ['o', 'oui', 'y', 'yes']:
                print("👋 Au revoir!")
                break

    except KeyboardInterrupt:
        print("\n\n👋 Programme interrompu. Au revoir!")
    except Exception as e:
        print(f"❌ Erreur critique: {str(e)}")

if __name__ == "__main__":
    main()



